indexedsearch:
  targetPid: 3
fcbigfoot:
  pages:
    privacy: 2
    contact: 4
  socialmedia:
    channels:
      instagram:
        link: 'https://www.instagram.com/typo3_official/'
  logo: 'EXT:wave_cart/Resources/Public/Icons/logo.svg'
  favicon: 'EXT:wave_cart/Resources/Public/Icons/logo.svg'
waveCart:
  cartPid: 102
  orderPid: 102
  orderItemPid: 102
  cartPageId: 105
  cartItemPid: 102
