categories:
  WaveCart:
    label: 'Wave Cart'

settings:
  waveCart.cartPageId:
    label: 'Cart Page Id'
    category: WaveCart
    description: 'Pages id on which the shopping cart is located'
    type: int
    default: 1  
